version: "3.8"

name: svelte-blog-starter-dev

services:
  blog:
    restart: on-failure
    build:
      context: ../
      dockerfile: images/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../src:/usr/src/app/src
      - ../static:/usr/src/app/static
      - ../vite.config.ts:/usr/src/app/vite.config.ts
      - ../svelte.config.js:/usr/src/app/svelte.config.js
      - ../postcss.config.cjs:/usr/src/app/postcss.config.cjs
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: bun --bun run dev --host
    environment:
      - PORT=5173
      - HOST=0.0.0.0
    networks:
      - blog-network
      - minio-network
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - blog-network
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minio-network
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=blog

networks:
  minio-network:
    driver: bridge
  blog-network:
    driver: bridge

volumes:
  minio_data:
    driver: local

